### ISSUE TITLE
@honghyunin CurrentUserUtil 에 올바르지 않은 코드 발견

### ISSUE THREAD

**Issue by KyungJunNoh** [Frame-in-Puzzle/Puzzle-Server#51]
### 테스트 코드를 짜던 중 올바르지 않는 코드 발견
- getCurrentUser() 에서 .getUsername()을 사용하는데, 제가 봤을때에는 name의 변수 값에 **유니크 값이 아닌 그냥 일반적인 이름을 가져와지는 것 같습니다.** 
- 이렇게 했을때의 문제점은 userRepository.findByName(name); 을 했을때, 동명이인이 가입되어있다면 **getCurrentUser()을 사용하는 모든 로직에서 같은 이름인 사용자들은 모두 에러가 날 것입니다.**
- 왜냐하면, 같은 이름이 두명이 가입되어있다면 findByName()은 단일조회 인데 두개이상이기 때문에 Exception이 터집니다.
- 그렇기 때문에 **우선, getUsername() 의 값을 알아보고 ( printf, log4j, test 코드 등등.. )** name 대신 유니크값을 가지는 githubId(혹은 다른 유니크 값을 가지는 컬럼)를 조회 할 수 있게 해야 할 것같습니다.
<img width="915" alt="2022-03-03_08-24-01" src="https://user-images.githubusercontent.com/68670670/156466727-97a82483-90a3-4c09-ade8-2ac62e1a80fd.png">

@honghyunin 
잘 모르겠는 로직이나 궁금한게 있으시면 연락주세요.
빠른 처리 부탁드립니다.

**Comment by honghyunin** [comment]
해당 이슈가 해결되어 close합니다 (#52)
